// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-upcoming-events.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var list_upcoming_events_default = defineTool({
  name: "list_upcoming_events",
  title: "List upcoming events",
  description: "List Regamos Foundation upcoming events/programs (title, dates, location, registration URL).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max events to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("upcoming_programs").select("id,title,description,start_date,end_date,location,registration_url,status").neq("status", "completed").order("start_date", { ascending: true }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_blog_posts_default = defineTool2({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List Regamos Foundation blog posts, optionally filtered by category.",
  inputSchema: {
    category: z2.string().optional().describe("Filter by category (Empowerment, Education, Community, Youth Development, Programs, Mental Health)."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max posts to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("blog_posts").select("id,title,excerpt,category,author,published_at,view_count,image_url").order("published_at", { ascending: false }).limit(limit ?? 10);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var get_blog_post_default = defineTool3({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch a single blog post by id, including full HTML content.",
  inputSchema: { id: z3.string().uuid().describe("Blog post id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("blog_posts").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Post not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/register-for-event.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function userClient(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var register_for_event_default = defineTool4({
  name: "register_for_event",
  title: "Register for event",
  description: "Register the signed-in user for a Regamos Foundation upcoming event.",
  inputSchema: {
    program_id: z4.string().uuid().describe("Upcoming program id to register for."),
    full_name: z4.string().trim().min(1).describe("Registrant full name."),
    phone: z4.string().trim().min(5).describe("Registrant phone number.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ program_id, full_name, phone }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return { content: [{ type: "text", text: "Signed-in user has no email claim" }], isError: true };
    }
    const { data, error } = await userClient(ctx).from("event_registrations").insert({ program_id, full_name, phone, email }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Registered for event. Registration id: ${data.id}` }],
      structuredContent: { registration: data }
    };
  }
});

// src/lib/mcp/tools/list-my-notifications.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
function userClient2(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_notifications_default = defineTool5({
  name: "list_my_notifications",
  title: "List my notifications",
  description: "List the signed-in user's in-app notifications.",
  inputSchema: {
    unread_only: z5.boolean().optional().describe("Return only unread notifications."),
    limit: z5.number().int().min(1).max(100).optional().describe("Max items (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = userClient2(ctx).from("notifications").select("id,type,title,message,is_read,created_at,metadata").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (unread_only) query = query.eq("is_read", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/mark-notification-read.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^4.4.3";
function userClient3(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var mark_notification_read_default = defineTool6({
  name: "mark_notification_read",
  title: "Mark notification read",
  description: "Mark one of the signed-in user's notifications as read.",
  inputSchema: { id: z6.string().uuid().describe("Notification id.") },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { error } = await userClient3(ctx).from("notifications").update({ is_read: true }).eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: "Notification marked as read." }] };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
function userClient4(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool7({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's Regamos Foundation profile (name, email, avatar).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await userClient4(ctx).from("profiles").select("id,full_name,email,avatar_url,created_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hlffhiutjqguedgnnblj";
var mcp_default = defineMcp({
  name: "regamos-foundation-mcp",
  title: "Regamos Foundation",
  version: "0.1.0",
  instructions: "Tools for the Regamos Foundation website. Read upcoming events and blog posts, register the signed-in user for an event, and manage their in-app notifications and profile.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_upcoming_events_default,
    list_blog_posts_default,
    get_blog_post_default,
    register_for_event_default,
    list_my_notifications_default,
    mark_notification_read_default,
    get_my_profile_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
